create table avis (
   idavis                    number generated by default as identity,
   note                      number not null,
   commentaire               varchar2(255 char),
   dateavis                  date not null,
   utilisateur_idutilisateur number not null,
   produit_idproduit         number not null
);

alter table avis add constraint avis_pk primary key ( idavis );

create table categorie (
   idcategorie          number generated by default as identity,
   nomcategorie         varchar2(50 char) not null,
   descriptioncategorie varchar2(255 char) not null
);

alter table categorie add constraint categorie_pk primary key ( idcategorie );

alter table categorie add constraint categorie_nomcategorie_un unique ( nomcategorie );

create table produit (
   idproduit             number generated by default as identity,
   nomproduit            varchar2(50 char) not null,
   descriptionproduit    varchar2(255 char) not null,
   prix                  number not null,
   disponibilite         varchar2(20 char) not null,
   categorie_idcategorie number not null
);

alter table produit add constraint produit_pk primary key ( idproduit );

create table reservation (
   idreservation             number generated by default as identity,
   datereservation           date not null,
   heurereservation          varchar2(5 char) not null,
   nombrepersonne            number not null,
   status                    varchar2(20 char) not null,
   commentaire               varchar2(255 char),
   utilisateur_idutilisateur number not null
);

alter table reservation add constraint reservation_pk primary key ( idreservation );

create table utilisateur (
   idutilisateur number generated by default as identity,
   nom           varchar2(50 char) not null,
   prenom        varchar2(50 char) not null,
   courriel      varchar2(80 char) not null,
   telephone     varchar2(20 char) not null,
   motdepasse    varchar2(255 char) not null,
   role          varchar2(20 char) not null,
   datecreation  date not null
);

alter table utilisateur add constraint utilisateur_pk primary key ( idutilisateur );

alter table utilisateur add constraint utilisateur_telephone_un unique ( telephone );

alter table utilisateur add constraint utilisateur_courriel_un unique ( courriel );

alter table avis
   add constraint avis_produit_fk
      foreign key ( produit_idproduit )
         references produit ( idproduit )
            on delete cascade;

alter table avis
   add constraint avis_utilisateur_fk
      foreign key ( utilisateur_idutilisateur )
         references utilisateur ( idutilisateur )
            on delete cascade;

alter table produit
   add constraint produit_categorie_fk
      foreign key ( categorie_idcategorie )
         references categorie ( idcategorie )
            on delete cascade;

alter table reservation
   add constraint reservation_utilisateur_fk
      foreign key ( utilisateur_idutilisateur )
         references utilisateur ( idutilisateur )
            on delete cascade;